---
name: Copilot Setup Steps

'on':
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/copilot-setup-steps.yml

jobs:
  copilot-setup-steps:
    runs-on: windows-2022
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
